#!/usr/bin/env python3
import os
import sys

import helpers
from analyzer import Analyzer
from termcolor import colored

# TODO -> Ya tenía elaborada cierta parte de este código, he pegado algunos trozos.

def main():
    if len(sys.argv) != 2:
    sys.exit("Modo de uso: ./tweets @nombre_de_usuario")

    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    analyzer = Analyzer(positives, negatives)

    screen_name = sys.argv[1].strip('@')

    tweets = helpers.get_user_timeline(screen_name, 50)

    if tweets == None:
        sys.exit("El usuario está privado o no existe")

     for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))

if __name__ == "__main__":
    main()